### PR TITLE
Use gradle and use reflection instead of compatibilities

### PR DESCRIPTION
**Pull request by supertassu**
Hey!

I've migrated the project to use Gradle as a build system and moved from the `Compatibility_1_XX_RX` to a single reflection class.

### CODE REVIEW

**Comment by supertassu** [comment]
> Everything looks good to me but I'm going to test it first..

Sure, go ahead!

**Comment by MrTheGood** [comment]
While I'm still waiting for some installations to complete, shall I add you as a contributor on SpigotMC?

**Comment by supertassu** [comment]
> While I'm still waiting for some installations to complete, shall I add you as a contributor on SpigotMC?

Go ahead when you've merged this PR. My spigot name is Tassu.

**Comment by MrTheGood** [comment]
Everything looks good to me. I'll accept the PR and create an update :)

**Pull request merged**
